/*
University of Illinois/NCSA Open Source License 

Copyright (c) 2018 Terrain Data, Inc. and the authors. All rights reserved.

Developed by: Terrain Data, Inc. and
              the individuals who committed the code in this file.
              https://github.com/terraindata/terrain
                  
Permission is hereby granted, free of charge, to any person 
obtaining a copy of this software and associated documentation files 
(the "Software"), to deal with the Software without restriction, 
including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software, 
and to permit persons to whom the Software is furnished to do so, 
subject to the following conditions:

* Redistributions of source code must retain the above copyright notice, 
  this list of conditions and the following disclaimers.

* Redistributions in binary form must reproduce the above copyright 
  notice, this list of conditions and the following disclaimers in the 
  documentation and/or other materials provided with the distribution.

* Neither the names of Terrain Data, Inc., Terrain, nor the names of its 
  contributors may be used to endorse or promote products derived from
  this Software without specific prior written permission.

This license supersedes any copyright notice, license, or related statement
following this comment block.  All files in this repository are provided
under the same license, regardless of whether a corresponding comment block
appears in them.  This license also applies retroactively to any previous
state of the repository, including different branches and commits, which
were made public on or after December 8th, 2018.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS WITH
THE SOFTWARE.
*/

// Copyright 2017 Terrain Data, Inc.

import ESAnyClause from './clauses/ESAnyClause';
import ESArrayClause from './clauses/ESArrayClause';
import ESBaseClause from './clauses/ESBaseClause';
import ESBooleanClause from './clauses/ESBooleanClause';
import ESClause from './clauses/ESClause';
import ESEnumClause from './clauses/ESEnumClause';
import ESFieldClause from './clauses/ESFieldClause';
import ESIndexClause from './clauses/ESIndexClause';
import ESMapClause from './clauses/ESMapClause';
import ESNullClause from './clauses/ESNullClause';
import ESNumberClause from './clauses/ESNumberClause';
import ESObjectClause from './clauses/ESObjectClause';
import ESPropertyClause from './clauses/ESPropertyClause';
import ESReferenceClause from './clauses/ESReferenceClause';
import ESStringClause from './clauses/ESStringClause';
import ESStructureClause from './clauses/ESStructureClause';
import ESTypeClause from './clauses/ESTypeClause';
import ESVariantClause from './clauses/ESVariantClause';

/* tslint:disable:max-line-length */

const EQLSpec: ESClause[] =
  [
    new ESAnyClause('any', { desc: 'Any valid JSON value.', url: 'http://www.json.org/' }),
    new ESBaseClause('base',
      {
        name: 'value',
        desc: 'A null, boolean, number, or string value.',
        url: 'http://www.json.org/',
      }),
    new ESNullClause('null', { desc: 'A null value.', url: 'http://www.json.org/' }),
    new ESBooleanClause('boolean', { desc: 'A boolean, either true or false.', url: 'http://www.json.org/' }),
    new ESNumberClause('number',
      {
        desc: 'A number. Numbers must begin with either \'-\', or a digit. For decimals type the leading zero (0.1234). For scientific notation use e or E to indicate the order of magnitude (1.23e10).',
        url: 'http://www.json.org/',
      }),
    new ESStringClause('string',
      {
        desc: 'A string. Strings are enclosed in double quotes ("example string"). Quotes and other special symbols can be encoded by escaping them. See json.org for more information.',
        url: 'http://www.json.org/',
      }),
    new ESObjectClause('object',
      {
        desc: 'A JSON object. Objects consist of name : value pairs enclosed in curly braces and separated by commas. See json.org for more information.',
        url: 'http://www.json.org/',
      }),
    new ESPropertyClause('property', {}),
    new ESFieldClause('field',
      {
        name: 'field',
        desc: 'The name of a document field.',
      }),
    new ESEnumClause('field_type',
      [
        'string',
        'number',
        'integer',
        'date',
        'boolean',
        'text',
        'keyword',
        'long',
        'short',
        'byte',
        'double',
        'float',
        'half_float',
        'scaled_float',
        'binary',
        'integer_range',
        'float_range',
        'long_range',
        'double_range',
        'date_range',
        'object',
        'nested',
        'geo_point',
        'geo_shape',
        'ip',
        'completion',
        'token_count',
        'murmur3',
        'attachment',
        'percolator',
      ],
      {}),
    new ESEnumClause('distance_unit',
      [
        'mi',
        'yd',
        'ft',
        'in',
        'km',
        'm',
        'cm',
        'mm',
        'nmi',
        'miles',
        'yards',
        'feet',
        'inch',
        'kilometers',
        'meters',
        'centimeters',
        'millimeters',
        'nauticalmiles',
        'NM',
      ],
      {}),
    new ESStructureClause('root',
      {
        index: 'index',
        type: 'type',
        from: 'from',
        size: 'size',
        body: 'body',
      },
      [],
      {
        name: 'root clause',
        desc: 'The outermost clause object that contains an entire search query.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html',
        template: { index: '', type: '', from: 0, size: 1000, body: null },
        autocomplete: ['index', 'type'],
      }),
    new ESIndexClause('index', { desc: 'Selects which index to search.' }),
    new ESTypeClause('type', { desc: 'Selects which type to search.' }),
    new ESNumberClause('from',
      {
        desc: 'How many results to skip over. This is usually used to implement pagination.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html',
      }),
    new ESNumberClause('size',
      {
        desc: 'How many results to return.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html',
      }),
    new ESStructureClause('body',
      {
        from: 'from',
        size: 'size',
        sort: 'sort_clause',
        track_scores: 'track_scores',
        _name: 'string',
        query: 'query',
        _source: '_source',
        stored_fields: 'string[]',
        script_fields: 'object',
        docvalue_fields: 'string[]',
        post_filter: 'query',
        highlight: 'object',
        rescore: 'object',
        explain: 'boolean',
        version: 'boolean',
        indices_boost: 'object',
        min_score: 'number',
        inner_hits: 'object',
        collapse: 'object',
        search_after: 'any[]',
        suggest: 'object',
        aggregations: 'any[]',
        aggs: 'any[]',
        cutoff_frequency: 'cutoff_frequency',
        minimum_should_match: 'minimum_should_match',
      },
      [],
      {
        name: 'body',
        desc: 'The object containing the filtering, sorting, matching, and aggregation logic for a query.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html',
        template: { query: null },
      }),
    new ESVariantClause('sort_clause',
      {
        object: 'sort',
        array: 'sort[]',
        string: 'field',
      },
      {
        desc: 'Controls the order in which results are returned. Results will be sorted by the first condition, and ties are broken by the second, and so on.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html',
      }),
    new ESVariantClause('sort',
      {
        object: '{field:sort_control}',
        string: 'field',
      },
      { url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html' }),
    new ESVariantClause('sort_control',
      {
        object: 'sort_settings',
        string: 'field',
      },
      {
        desc: 'Either "asc" or "desc", or a sort settings clause, {"order" : "asc"}',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html',
      }),
    new ESStructureClause('sort_settings',
      {
        'order': 'sort_order',
        'mode': 'sort_mode',
        'missing': 'sort_missing',
        'nested_path': 'sort_nested_path',
        'nested_filter': 'sort_nested_filter',
        'unmapped_type': 'sort_unmapped_type',
        'unit': 'distance_unit',
        'distance_type': 'distance_type',
        'pin.location': 'geo_points',
        'type': 'sort_field_type',
        'script': 'script',
      },
      [],
      { url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html' }),
    new ESEnumClause('sort_mode',
      ['min', 'max', 'sum', 'avg', 'median'],
      {
        desc: 'When sorting by an array or multi-valued field, controls how that field is used to sort results.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#_sort_mode_option',
      }),
    new ESEnumClause('sort_order',
      ['asc', 'desc'],
      {
        desc: 'The order to sort this field by: ascending or descending.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#_sort_order',
      }),
    new ESReferenceClause('sort_nested_path',
      'field',
      {
        name: 'nested path',
        desc: 'The name of the nested object to sort by.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#nested-sorting',
      }),
    new ESReferenceClause('sort_nested_filter',
      'query',
      {
        name: 'nested sort filter',
        desc: 'A query that filters the nested objects before using them to sort by.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#nested-sorting',
      }),
    new ESBaseClause('sort_missing',
      {
        name: 'missing value clause',
        desc: 'Sets how documents missing this sort field will be treated. The special values of _last and _first can be used to sort these documents after or before other results, or substitute value can be specified.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#_missing_values',
        template: '_last',
      }),
    new ESReferenceClause('sort_unmapped_type',
      'field_type',
      {
        name: 'unmapped type',
        desc: 'If no mapping is defined for this field, unmapped_type can be used to set what type the field is interpreted as.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#_ignoring_unmapped_fields',
      }),
    new ESReferenceClause('sort_field_type',
      'field_type',
      { desc: 'The type to interpret the result of the sort script as.' }),
    new ESBooleanClause('track_scores',
      {
        desc: 'When set to true, the Elastic _score field will be computed even when it isn\'t used to sort the results.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#_multiple_reference_points',
        template: true,
      }),
    new ESVariantClause('geo_points',
      {
        object: 'geo_point',
        array: 'geo_point[]',
      },
      {
        desc: 'Either a single geo point, or a list of several.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#_multiple_reference_points',
      }),
    new ESVariantClause('geo_point',
      { object: 'latlon_object', array: 'number[]', string: 'string' },
      {
        desc: 'Indicates a point location. Should be one of these: a lat-lon object, {"lat":40, "lon":-70}; a lat lon string, "40,-70"; a geohash, "drm3btev3e86"; or a lat lon array, [40, -70].',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#_lat_lon_as_properties',
      }),
    new ESStructureClause('latlon_object', { lat: 'number', lon: 'number' }, [], {}),
    new ESEnumClause('distance_type',
      ['arc', 'plane'],
      {
        desc: 'Chooses the distance formula to use. arc is the default, plane is faster but less accurate.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#geo-sorting',
        template: 'arc',
      }),
    new ESStructureClause('script',
      {
        lang: 'script_language',
        params: 'script_params',
        inline: 'script_inline',
        stored: 'script_name',
      },
      [],
      {}),
    new ESStringClause('script_inline',
      { desc: 'The code for this inline script' }),
    new ESMapClause('script_params', 'string', 'any',
      { desc: 'Parameters to pass to the script.' }),
    new ESEnumClause('script_language',
      ['painless', 'groovy', 'expression', 'mustache', 'javascript', 'python'],
      {
        desc: 'The scripting language to use.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting.html#_general_purpose_languages',
        template: 'painless',
      }),
    new ESStringClause('script_name',
      {
        desc: 'The name of the stored script to call.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-using.html#modules-scripting-stored-scripts',
      }),
    new ESVariantClause('_source',
      {
        object: 'includeExclude',
        boolean: 'boolean',
        string: 'field',
        array: 'field[]',
      },
      {
        name: 'source clause',
        desc: 'Controls which source fields are returned by this query',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-source-filtering.html',
      }),
    new ESStructureClause('includeExclude',
      {
        includes: 'field[]',
        excludes: 'field[]',
      },
      [],
      { name: 'include and exclude lists', desc: 'Filters in include values and out exclude values.' }),
    new ESStructureClause('query',
      {
        type: 'type',
        ids: 'string[]',
        term: 'term_query',
        terms: 'terms_query',
        range: 'range_query',
        exists: 'exists_query',
        prefix: 'prefix_query',
        wildcard: 'wildcard_query',
        regexp: 'regexp_query',
        fuzzy: 'fuzzy_query',
        match_all: 'match_all',
        match_none: 'match_none',
        match: 'match',
        match_phrase: 'match_phrase',
        match_phrase_prefix: 'match_phrase_prefix',
        multi_match: 'multi_match',
        common: 'common_terms_query',
        query_string: 'query_string_clause',
        simple_query_string: 'simple_query_string',
        constant_score: 'constant_score',
        bool: 'bool_query',
        dis_max: 'dis_max',
        function_score: 'any',
        script_score: 'script_score',
        boosting: 'boosting_query',
        nested: 'nested_query',
        has_child: 'has_child_query',
        has_parent: 'has_parent_query',
      },
      [],
      {
        name: 'query',
        desc: 'Controls match, term, and range filtering and matching.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-query.html',
        template: { bool: null },
      }),
    new ESArrayClause('ids',
      'string',
      {
        name: 'ids clause',
        desc: 'Selects a set of document ids to search within.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-ids-query.html',
      }),
    new ESReferenceClause('constant_score',
      'query',
      {
        name: 'constant score query',
        desc: 'A query clause that is not used to compute result scores.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-constant-score-query.html',
      }),
    new ESStructureClause('bool_query',
      {
        must: 'must',
        must_not: 'must_not',
        filter: 'filter',
        should: 'should',
        minimum_should_match: 'minimum_should_match',
      },
      [],
      {
        name: 'bool',  
        desc: 'Filters in and out documents meeting the given logical conditions.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-filter-context.html',
        // template: { must: null, must_not: null, should: null, minimum_should_match: null },
      }),
    new ESVariantClause('must',
      {
        object: 'query',
        array: 'query[]',
      },
      {
        name: 'must clause',
        desc: 'All results must match this subquery. The better a result matches, the higher its __score will be. The must clause may be a single query object, or an array of query objects.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html',
      }),
    new ESVariantClause('must_not',
      {
        object: 'query',
        array: 'query[]',
      },
      {
        name: 'must not clause',
        desc: 'All results must not match this query. Filters out documents that match this subquery. The must not clause may be a single query object, or an array of query objects.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html',
      }),
    new ESReferenceClause('filter',
      'query',
      {
        name: 'filter context clause',
        desc: 'Query conditions in a filter clause aren\'t used when computing a document\'s elastic __score.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html#_scoring_with_literal_bool_filter_literal',
      }),
    new ESVariantClause('should',
      {
        object: 'query',
        array: 'query[]',
      },
      {
        name: 'should clause',
        desc: 'Results should match this query. The better a result matches, the higher its __score will be. Also see minimum_should_match. The should clause may be a single query object, or an array of query objects.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html',
      }),
    new ESVariantClause('minimum_should_match',
      {
        number: 'number',
        string: 'string',
      },
      {
        name: 'minimum should match',
        desc: 'Controls how many or what percentage of should clauses are required to match.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-minimum-should-match.html',
      }),
    new ESMapClause('term_query',
      'field',
      'term_value',
      {
        desc: 'Matches documents that contain an exact match for the given term.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html',
      }),
    new ESVariantClause('term_value',
      {
        object: 'term_settings',
        null: 'null',
        boolean: 'boolean',
        number: 'number',
        string: 'string',
      },
      { required: ['value'] }),
    new ESStructureClause('term_settings',
      {
        value: 'base',
        boost: 'boost',
      },
      ['value'], {}),
    new ESMapClause('terms_query',
      'field',
      'terms_value',
      {
        desc: 'Matches documents that contain an exact match for any of the given terms. Can also be populated by a terms lookup clause.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-terms-query.html',
      }),
    new ESVariantClause('terms_value',
      {
        object: 'terms_lookup',
        array: 'any[]',
      }, {}),
    new ESStructureClause('terms_lookup',
      {
        index: 'index',
        type: 'type',
        id: 'terms_lookup_id',
        path: 'terms_lookup_path',
        routing: 'string',
      },
      ['value'],
      {}),
    new ESStringClause('terms_lookup_id',
      {
        name: 'id',
        desc: 'The id of the document to query inside a terms lookup clause.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-terms-query.html',
      }),
    new ESStringClause('terms_lookup_path',
      {
        name: 'path',
        desc: 'The field to get the term values from in the lookup document.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-terms-query.html',
      }),
    new ESMapClause('range_query',
      'field',
      'range_value',
      {
        desc: 'Matches documents that have a value within the specified range.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-range-query.html',
      }),
    new ESStructureClause('range_value',
      {
        gt: 'base',
        gte: 'base',
        lt: 'base',
        lte: 'base',
        boost: 'boost',
      },
      [],
      {}),
    new ESStructureClause('exists_query',
      {
        field: 'field',
        null_value: 'base',
      },
      ['field'],
      {
        desc: 'Matches documents that have one or more non-null values in the specified field.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-exists-query.html',
      }),
    new ESMapClause('prefix_query',
      'field',
      'prefix_query_value',
      {
        desc: 'Matches documents that contain terms with the given prefix.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-prefix-query.html',
      }),
    new ESVariantClause('prefix_query_value',
      {
        object: 'prefix_query_settings',
        null: 'base',
        boolean: 'base',
        number: 'base',
        string: 'base',
      },
      {}),
    new ESStructureClause('prefix_query_settings',
      {
        value: 'base',
        boost: 'boost',
      },
      ['value'],
      { url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-prefix-query.html' }),
    new ESMapClause('wildcard_query',
      'field',
      'wildcard_query_value',
      {
        desc: 'Matches documents using a wildcard expression.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-wildcard-query.html',
      }),
    new ESVariantClause('wildcard_query_value',
      {
        object: 'wildcard_query_settings',
        null: 'base',
        boolean: 'base',
        number: 'base',
        string: 'base',
      },
      {}),
    new ESStructureClause('wildcard_query_settings',
      {
        value: 'base',
        boost: 'boost',
      },
      ['value'],
      { url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-wildcard-query.html' }),
    new ESMapClause('regexp_query',
      'field',
      'regexp_query_value',
      {
        desc: 'Matches documents using a regular expression.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html',
      }),
    new ESVariantClause('regexp_query_value',
      {
        object: 'regexp_query_settings',
        null: 'base',
        boolean: 'base',
        number: 'base',
        string: 'base',
      },
      {}),
    new ESStructureClause('regexp_query_settings',
      {
        value: 'base',
        boost: 'boost',
        flags: 'string',
      },
      ['value'],
      { url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html' }),
    new ESMapClause('fuzzy_query',
      'field',
      'fuzzy_query_value',
      {
        desc: 'Can help to make inexact matches in the case of misspellings or multiple spellings of words. The maximum Levenshtein edit distance to expand words (terms) to. The higher this is, the slower and broader queries will be. When applied to a numeric value, the fuzziness is the additional +/- margin that a match can have from the queried value.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-fuzzy-query.html',
      }),
    new ESVariantClause('fuzzy_query_value',
      {
        object: 'fuzzy_query_settings',
        null: 'base',
        boolean: 'base',
        number: 'base',
        string: 'base',
      },
      {}),
    new ESStructureClause('fuzzy_query_settings',
      {
        value: 'base',
        boost: 'boost',
        fuzziness: 'fuzziness',
        prefix_length: 'fuzzy_prefix_length',
        max_expansions: 'fuzzy_max_expansions',
      },
      ['value'],
      { url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-fuzzy-query.html' }),
    new ESNumberClause('boost',
      {
        desc: 'Boosts the score of matches by the given amount. Boosts are not exactly multiplicative.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/guide/current/_boosting_query_clauses.html',
      }),
    new ESStructureClause('match_all',
      { boost: 'boost' },
      [],
      {
        name: 'match all clause',
        desc: 'Matches all documents.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-all-query.html',
      }),
    new ESMapClause('match_none',
      'field',
      'match_value',
      {
        name: 'match none clause',
        desc: 'Matches no documents.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-all-query.html#query-dsl-match-none-query',
      }),
    new ESMapClause('match',
      'field',
      'match_value',
      {
        name: 'match clause',
        desc: 'Does an analyzed (full-text) match on the given term.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html',
      }),
    new ESVariantClause('match_value',
      {
        object: 'match_settings',
        null: 'base',
        boolean: 'base',
        number: 'base',
        string: 'base',
      },
      {}),
    new ESStructureClause('match_settings',
      {
        query: 'string',
        operator: 'match_operator',
        zero_terms_query: 'zero_terms_query',
        cutoff_frequency: 'cutoff_frequency',
        fuzziness: 'fuzziness',
        fuzzy_transpositions: 'fuzzy_transpositions',
        fuzzy_rewrite: 'rewrite',
        analyzer: 'analyzer',
        prefix_length: 'fuzzy_prefix_length',
        max_expansions: 'fuzzy_max_expansions',
        slop: 'slop',
        lenient: 'boolean',
      },
      ['query'],
      {
        template: {
          query: '',
          operator: null,
        },
      }),
    new ESEnumClause('match_operator',
      ['and', 'or'],
      {
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html#query-dsl-match-query-zero',
        template: 'or',
      }),
    new ESEnumClause('zero_terms_query',
      ['none', 'all'],
      { url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html#query-dsl-match-query-zero' }),
    new ESNumberClause('cutoff_frequency',
      {
        desc: 'How common a word (term) needs to be before it is moved into a subquery that is only used if the uncommon words match.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html#query-dsl-match-query-cutoff',
        template: '0.1',
      }),
    new ESBaseClause('fuzziness',
      {
        desc: 'Can help to make inexact matches in the case of misspellings or multiple spellings of words. The maximum Levenshtein edit distance to expand words (terms) to. The higher this is, the slower and broader queries will be. When applied to a numeric value, the fuzziness is the additional +/- margin that a match can have from the queried value.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#fuzziness',
        template: 'AUTO',
        suggestions: ['AUTO', 0, 1, 2],
      }),
    new ESBooleanClause('fuzzy_transpositions',
      {
        desc: 'Sets if transpositions are allowed when computing fuzzy matches.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html#query-dsl-match-query-fuzziness',
        template: 'true',
      }),
    new ESEnumClause('slop',
      [0, 1, 2],
      {
        desc: 'How many word (term) transpositions are tolerated when matching a phrase.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query-phrase.html',
        template: 0,
      }),
    new ESStringClause('analyzer',
      {
        desc: 'Chooses which analyzer to use to convert strings into lists of words (tokens) when searching.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-analyzers.html',
        template: 'standard',
        suggestions: [
          'standard',
          'english',
          'simple',
          'whitespace',
          'stop',
          'keyword',
          'pattern',
          'fingerprint',
          'arabic',
          'armenian',
          'basque',
          'brazilian',
          'bulgarian',
          'catalan',
          'cjk',
          'czech',
          'danish',
          'dutch',
          'english',
          'finnish',
          'french',
          'galician',
          'german',
          'greek',
          'hindi',
          'hungarian',
          'indonesian',
          'irish',
          'italian',
          'latvian',
          'lithuanian',
          'norwegian',
          'persian',
          'portuguese',
          'romanian',
          'russian',
          'sorani',
          'spanish',
          'swedish',
          'turkish',
          'thai',
        ],
      }),
    new ESNumberClause('fuzzy_prefix_length',
      {
        desc: 'When using fuzzy matching, this and max_expansions configures fuzzy matching.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html#query-dsl-match-query-fuzziness',
        template: '1',
      }),
    new ESNumberClause('fuzzy_max_expansions',
      {
        name: 'maximum prefix expansions',
        desc: 'Number of suffixes that fuzzy terms are expanded into when matching words. The more expansions, the broader and slower the query will be.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html#query-dsl-match-query-fuzziness',
        template: 50,
      }),
    new ESEnumClause('rewrite',
      [
        'constant_score',
        'scoring_boolean',
        'constant_score',
        'top_terms_1',
        'top_terms_2',
        'top_terms_3',
        'top_terms_4',
        'top_terms_boost_1',
        'top_terms_boost_2',
        'top_terms_boost_3',
        'top_terms_boost_4',
        'top_terms_blended_freqs_1',
        'top_terms_blended_freqs_2',
        'top_terms_blended_freqs_3',
        'top_terms_blended_freqs_4',
      ],
      {
        desc: 'Chooses what method is used to rewrite multi term queries.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-term-rewrite.html#query-dsl-multi-term-rewrite',
        template: 'constant_score',
      }),
    new ESStructureClause('dis_max',
      {
        tie_breaker: 'dis_max_tie_breaker',
        boost: 'boost',
        queries: 'query[]',
      },
      ['queries'],
      {
        name: 'dis max query',
        desc: 'Combines results from each of the given queries, ordering results by their maximum score in each query.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-dis-max-query.html',
      }),
    new ESNumberClause('dis_max_tie_breaker',
      {
        name: 'tie breaker',
        desc: 'Boosts documents that contain the same term in multiple fields.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-dis-max-query.html',
        template: 0,
      }),
    new ESStructureClause('script_score',
      {
        script: 'script',
      },
      ['script'],
      {
        desc: 'Customizes the scoring of a subquery using a script.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-script-score',
      }),
    new ESStructureClause('boosting_query',
      {
        positive: 'query',
        negative: 'query',
        negative_boost: 'boost',
      },
      [],
      {
        desc: 'Reduces the score of results that match the given query.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-boosting-query.html',
      }),
    new ESMapClause('match_phrase',
      'field',
      'match_phrase_value',
      {
        name: 'match phrase query',
        desc: 'Makes a phrase query using analyzed text. Matches documents containing the words (tokens) in the phrase text.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query-phrase.html',
      }),
    new ESVariantClause('match_phrase_value',
      {
        object: 'match_settings',
        string: 'query_string',
      },
      {}),
    new ESMapClause('match_phrase_prefix',
      'field',
      'match_phrase_prefix_value',
      {
        name: 'match phrase prefix query',
        desc: 'Makes a query using analyzed text which matches on all terms and any term starting with the prefix of the last term in the phrase text.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query-phrase-prefix.html',
      }),
    new ESVariantClause('match_phrase_prefix_value',
      {
        object: 'match_settings',
        string: 'query_string',
      },
      {}),
    new ESStructureClause('multi_match',
      {
        query: 'query_string',
        fields: 'multi_match_field',
        type: 'multi_match_type',
        tie_breaker: 'multi_match_tie_breaker',
      },
      ['query', 'fields'],
      {
        name: 'multi match query',
        desc: 'A match query that allows multi-field queries',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html',
      }),
    new ESArrayClause('multi_match_field', 'field',
      {
        desc: 'A list of fields to match against.',
      }),
    new ESEnumClause('multi_match_type',
      [
        'best_fields',
        'most_fields',
        'cross_fields',
        'phrase',
        'phrase_prefix',
      ],
      {
        desc: 'Sets how the multi match query finds and scores documents.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html#multi-match-types',
        template: 'best_fields',
      }),
    new ESNumberClause('multi_match_tie_breaker',
      {
        name: 'tie breaker',
        desc: 'A setting of 0 causes the query to use the best score out of each field\'s match; a setting of 1 causes the query to add all of the scores. Settings in between are a blend of these methods.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html#_literal_tie_breaker_literal',
        template: 0,
      }),
    new ESReferenceClause('common_terms_query',
      'root',
      {
        desc: 'A query which breaks the query words (terms) into common and uncommon sets. Matches on uncommon words are given more weight than matches on common words.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-common-terms-query.html',
      }),
    new ESStructureClause('query_string_clause',
      {
        query: 'query_string',
        default_field: 'query_string_default_field',
        default_operator: 'query_string_default_operator',
        analyzer: 'analyzer',
        allow_leading_wildcard: 'boolean',
        enable_position_increments: 'boolean',
        fuzzy_max_expansions: 'fuzzy_max_expansions',
        fuzziness: 'fuzziness',
        fuzzy_prefix_length: 'fuzzy_prefix_length',
        phrase_slop: 'slop',
        boost: 'boost',
        auto_generate_phrase_queries: 'boolean',
        analyze_wildcard: 'boolean',
        max_determinized_states: 'number',
        minimum_should_match: 'minimum_should_match',
        lenient: 'lenient',
        time_zone: 'string',
        quote_field_suffix: 'string',
        split_on_whitespace: 'boolean',
        all_fields: 'boolean',
        use_dis_max: 'boolean',
        tie_breaker: 'dis_max_tie_breaker',
      },
      ['query'],
      {
        desc: 'Uses a query parser to parse its content so that operators like AND and OR can be used inside a query string.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html',
      }),
    new ESReferenceClause('query_string_default_field',
      'field',
      {
        name: 'default field',
        desc: 'Defines which field is queried when no prefix is specified.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html',
        template: '_all',
      }),
    new ESEnumClause('query_string_default_operator',
      ['AND', 'OR'],
      {
        template: 'OR',
        name: 'default operator',
        desc: 'Defines how consecutive terms in the query are combined.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html',
      }),
    new ESStructureClause('nested_query',
      {
        path: 'field',
        score_mode: 'nested_score_mode',
        query: 'query',
        ignore_unmapped: 'ignore_unmapped',
      },
      [],
      {
        desc: 'Queries nested documents.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-nested-query.html',
        template: {
          path: '',
          score_mode: null,
          query: null,
        },
      }),
    new ESEnumClause('nested_score_mode',
      ['avg', 'sum', 'min', 'max', 'none'],
      {
        name: 'score mode',
        desc: 'Controls the way in which nested document matching adjusts the score of the parent document.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-nested-query.html',
        template: 'avg',
      }),
    new ESStructureClause('has_child_query',
      {
        type: 'field',
        score_mode: 'has_child_score_mode',
        min_children: 'number',
        max_children: 'number',
        ignore_unmapped: 'ignore_unmapped',
        query: 'query',
      },
      ['type', 'query'],
      {
        desc: 'Matches documents that have nested (child) documents that match this query',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-has-child-query.html',
        template: {
          type: '',
          score_mode: null,
          query: null,
        },
      }),
    new ESEnumClause('has_child_score_mode',
      ['avg', 'sum', 'min', 'max', 'none'],
      {
        name: 'score mode',
        desc: 'Controls the way in which nested document matching adjusts the score of the parent document.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-has-child-query.html',
        template: 'none',
      }),
    new ESStructureClause('has_parent_query',
      {
        parent_type: 'type',
        score: 'has_parent_score',
        ignore_unmapped: 'ignore_unmapped',
        query: 'query',
      },
      ['parent_type', 'query'],
      {
        desc: 'Query that returns nested (child) documents that have parents that match the query.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-has-parent-query.html',
        template: {
          parent_type: '',
          score: null,
          query: null,
        },
      }),
    new ESBooleanClause('has_parent_score',
      {
        desc: 'If set to false, the document score is set to the boost on the has_parent query. If set to true, the score of the parent document is used to score the child documents.',
        template: false,
      }),
    new ESBooleanClause('ignore_unmapped',
      {
        desc: 'If unmapped paths should be ignored.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-has-child-query.html#_ignore_unmapped',
        template: false,
      }),
    new ESStructureClause('simple_query_string',
      {
        query: 'query_string',
        fields: 'field[]',
        default_operator: 'query_string_default_operator',
        analyzer: 'analyzer',
        flags: 'string',
        analyze_wildcard: 'boolean',
        minimum_should_match: 'minimum_should_match',
        lenient: 'lenient',
        quote_field_suffix: 'string',
        all_fields: 'boolean',
      },
      ['query'],
      {
        name: 'simple query string clause',
        desc: 'A simplified version of a query string clause that works even when the query string is malformed.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html',
      }),
    new ESStringClause('query_string',
      {
        name: 'query string',
        desc: 'The text to match. This text will be analyzed (broken into words) and elastic will find documents containing those words. Some additional syntax is allowed in query strings; see the documentation for more information.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-syntax',
      }),
    new ESBooleanClause('lenient',
      {
        desc: 'Whether or not query string formatting errors should be ignored.',
        url: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html',
      }),
  ];

export default EQLSpec;
