# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_tconnector', [dirname(__file__)])
        except ImportError:
            import _tconnector
            return _tconnector
        if fp is not None:
            try:
                _mod = imp.load_module('_tconnector', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _tconnector = swig_import_helper()
    del swig_import_helper
else:
    import _tconnector
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class TQLResult(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TQLResult, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TQLResult, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _tconnector.delete_TQLResult
    __del__ = lambda self : None;
    def __iter__(self) -> "TQLResult *" : return _tconnector.TQLResult___iter__(self)
    def __next__(self) -> "PyObject *" : return _tconnector.TQLResult___next__(self)
    def ref(self) -> "void" : return _tconnector.TQLResult_ref(self)
    def unref(self) -> "void" : return _tconnector.TQLResult_unref(self)
TQLResult_swigregister = _tconnector.TQLResult_swigregister
TQLResult_swigregister(TQLResult)

class TConnection(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TConnection, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TConnection, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _tconnector.delete_TConnection
    __del__ = lambda self : None;
    def query(self, *args) -> "TQLResult *" : return _tconnector.TConnection_query(self, *args)
    def send(self, *args) -> "TQLResult *" : return _tconnector.TConnection_send(self, *args)
    def ref(self) -> "void" : return _tconnector.TConnection_ref(self)
    def unref(self) -> "void" : return _tconnector.TConnection_unref(self)
TConnection_swigregister = _tconnector.TConnection_swigregister
TConnection_swigregister(TConnection)


def tql_connect(*args) -> "TConnection *" :
  return _tconnector.tql_connect(*args)
tql_connect = _tconnector.tql_connect
# This file is compatible with both classic and new-style classes.


